### ISSUE TITLE
Rubycritic gem installation to insurance the code quality

### ISSUE THREAD

**Issue by TecnoSigma** [locaweb/heartcheck-sidekiq#19]
I verified that missing gems to insurance the code quality.

That's why I suggest that, please, install the [Rubycritic](https://github.com/whitesmith/rubycritic) gem in the project.

Observation: The configured minimum score must be the first score that the gem create.

Thanks. :smiley:

**Comment by maniSHarma7575** [comment]
@VictorSNA @TecnoSigma  I want to work on it. Added a MR please review.

**Comment by maniSHarma7575** [comment]
#21

**Comment by VictorSNA** [comment]
Thanks!
